config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  patch '/notes/:id/save_content', to:'notes#save_content'
  post 'notes/:id/toggle_favorite', to: "notes#toggle_favorite", as: :toggle_favorite
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :notes do
    collection do
      get 'search'
    end
  end

  resources :ycourses, only: [:new, :create, :destroy]

  resources :favourite_notes, as: :fnote

  get '/tagged', to: "notes#tagged", as: :tagged
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :ycourse

  has_many :favourite_notes

  acts_as_taggable_on :tags

  acts_as_favoritable
end

app/controllers/notes_controller.rb
# require 'pry-byebug'

class NotesController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :tagged]
before_action :set_note, only: [:toggle_favorite, :show, :edit, :update, :destroy, :save_content]
protect_from_forgery except: :update

  def index
    @notes = Note.all || "0"
    @notes = policy_scope(Note).order(created_at: :desc)
    @current_user = current_user
    @ycourses = Ycourse.all || "0"

    @ycourses_url = @ycourses.map do |ycourse|
      get_youtube_id(ycourse.url)
    end

    if params[:search].present?
      @search_notes = Note.where("text_content ILIKE ?", "%#{params[:search]}%")
      @search_ycourse = @search_notes.map.with_index do |ycourse, index|
        get_youtube_id(Ycourse.find(@search_notes.find(@ycourses[index].id).id).url)
      end


    else
      @search_notes = @notes
    end
  end

  def show
    authorize @note
    @ycourse = Ycourse.find(params[:id]) || "0"
    @ycourseID = get_youtube_id(@ycourse.url)
    @related_notes = @note.find_related_tags
  end

  def new
    @note = Note.new
    @ycourse = Ycourse.new
    @note.ycourse = @ycourse
    authorize @note
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    authorize @note
    if @note.save
      redirect_to note_path(@note), notice: "A new Note has been created!"
    else
      render :new
    end
  end

  def edit
    authorize @note
  end

  def update
    authorize @note
    if @note.update(note_params)
      redirect_to @note, notice: 'Your Note was successfully updated'
    else
      render :edit
    end
  end

  def save_content
    authorize @note
    if @note.update(note_params)
      @note.text_content= JSON.parse(@note.json_content)
      @note.save


      respond_to do |format|
        format.json {render :show}
      end
    else
      render json: { error: "record has not been save, sorry!" }, status: 422
    end
  end

  def tagged
    if params[:tag].present?
      @notes = Note.tagged_with(params[:tag])
    else
      @notes = Note.all
    end
  end

  def destroy
    authorize @note
    @note.destroy
    redirect_to notes_url, notice: 'Your Note was successfully destroyed'
  end

  def toggle_favorite
    authorize @note
    if current_user.favorited?(@note)
      current_user.unfavorite(@note)
    else
      current_user.favorite(@note)
    end
    redirect_to note_path(@note), notice: "Note #{current_user.favorited?(@note) ? "added to" : "removed from"} favorites"
  end

  private

  def note_params
    params.require(:note).permit(:title, :json_content, :visible, tag_list: [])
  end

  def set_note
    @note = Note.find(params[:id])
  end

  def get_youtube_id(url)
    url = url.gsub(/(>|<)/i, '').split(%r{(vi/|v=|/v/|youtu\.be/|/embed/)})
    return url if url[2].nil?

    id = url[2].split(/[^0-9a-z_\-]/i)
    id[0]
  end
end

app/views/notes/_editeur.html.erb
<!-- Load Tools -->
  <!--
   You can upload Tools to your project's directory and connect them by relative links.
   Also you can load each Tool from CDN or use NPM/Yarn packages.
   Read more at Tools Connection doc:
   https://editorjs.io/getting-started#tools-connection
   -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script><!-- Header -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/simple-image@latest"></script><!-- Image -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/delimiter@latest"></script><!-- Delimiter -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script><!-- List -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/checklist@latest"></script><!-- Checklist -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/quote@latest"></script><!-- Quote -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/code@latest"></script><!-- Code -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/embed@latest"></script><!-- Embed -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/table@latest"></script><!-- Table -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/link@latest"></script><!-- Link -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/warning@latest"></script><!-- Warning -->

  <script src="https://cdn.jsdelivr.net/npm/@editorjs/marker@latest"></script><!-- Marker -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/inline-code@latest"></script><!-- Inline Code -->

  <!-- Load Editor.js's Core -->
  <script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>

  <!-- Initialization -->
  <script>
    /**
     * To initialize the Editor, create a new instance with configuration object
     * @see docs/installation.md for mode details
     */
    var editor = new EditorJS({
      /**
       * Enable/Disable the read only mode
       */
      readOnly: false,

      /**
       * Wrapper of Editor
       */
      holder: 'editorjs',

      /**
       * Common Inline Toolbar settings
       * - if true (or not specified), the order from 'tool' property will be used
       * - if an array of tool names, this order will be used
       */
      // inlineToolbar: ['link', 'marker', 'bold', 'italic'],
      // inlineToolbar: true,

      /**
       * Tools list
       */
      tools: {
        /**
         * Each Tool is a Plugin. Pass them via 'class' option with necessary settings {@link docs/tools.md}
         */
        header: {
          class: Header,
          inlineToolbar: ['marker', 'link'],
          config: {
            placeholder: 'Header'
          },
          shortcut: 'CMD+SHIFT+H'
        },

        /**
         * Or pass class directly without any configuration
         */
        image: SimpleImage,

        list: {
          class: List,
          inlineToolbar: true,
          shortcut: 'CMD+SHIFT+L'
        },

        checklist: {
          class: Checklist,
          inlineToolbar: true,
        },

        quote: {
          class: Quote,
          inlineToolbar: true,
          config: {
            quotePlaceholder: 'Enter a quote',
            captionPlaceholder: 'Quote\'s author',
          },
          shortcut: 'CMD+SHIFT+O'
        },

        warning: Warning,

        marker: {
          class:  Marker,
          shortcut: 'CMD+SHIFT+M'
        },

        code: {
          class:  CodeTool,
          shortcut: 'CMD+SHIFT+C'
        },

        delimiter: Delimiter,

        inlineCode: {
          class: InlineCode,
          shortcut: 'CMD+SHIFT+C'
        },

        linkTool: LinkTool,

        embed: Embed,

        table: {
          class: Table,
          inlineToolbar: true,
          shortcut: 'CMD+ALT+T'
        },

      },

      /**
       * This Tool will be used as default
       */
      // defaultBlock: 'paragraph',

      /**
       * Initial Editor data
       */
      data: {
        blocks: [
          {
            type: "header",
            data: {
              text: "Editor.js",
              level: 2
            }
          },
          {
            type : 'paragraph',
            data : {
              text : 'Hey. Meet the new Editor. On this page you can see it in action — try to edit this text. Source code of the page contains the example of connection and configuration.'
            }
          },
          {
            type: "header",
            data: {
              text: "Key features",
              level: 3
            }
          },
          {
            type : 'list',
            data : {
              items : [
                'It is a block-styled editor',
                'It returns clean data output in JSON',
                'Designed to be extendable and pluggable with a simple API',
              ],
              style: 'unordered'
            }
          },
          {
            type: "header",
            data: {
              text: "What does it mean «block-styled editor»",
              level: 3
            }
          },
          {
            type : 'paragraph',
            data : {
              text : 'Workspace in classic editors is made of a single contenteditable element, used to create different HTML markups. Editor.js <mark class=\"cdx-marker\">workspace consists of separate Blocks: paragraphs, headings, images, lists, quotes, etc</mark>. Each of them is an independent contenteditable element (or more complex structure) provided by Plugin and united by Editor\'s Core.'
            }
          },
          {
            type : 'paragraph',
            data : {
              text : `There are dozens of <a href="https://github.com/editor-js">ready-to-use Blocks</a> and the <a href="https://editorjs.io/creating-a-block-tool">simple API</a> for creation any Block you need. For example, you can implement Blocks for Tweets, Instagram posts, surveys and polls, CTA-buttons and even games.`
            }
          },
          {
            type: "header",
            data: {
              text: "What does it mean clean data output",
              level: 3
            }
          },
          {
            type : 'paragraph',
            data : {
              text : 'Classic WYSIWYG-editors produce raw HTML-markup with both content data and content appearance. On the contrary, Editor.js outputs JSON object with data of each Block. You can see an example below'
            }
          },
          {
            type : 'paragraph',
            data : {
              text : `Given data can be used as you want: render with HTML for <code class="inline-code">Web clients</code>, render natively for <code class="inline-code">mobile apps</code>, create markup for <code class="inline-code">Facebook Instant Articles</code> or <code class="inline-code">Google AMP</code>, generate an <code class="inline-code">audio version</code> and so on.`
            }
          },
          {
            type : 'paragraph',
            data : {
              text : 'Clean data is useful to sanitize, validate and process on the backend.'
            }
          },
          {
            type : 'delimiter',
            data : {}
          },
          {
            type : 'paragraph',
            data : {
              text : 'We have been working on this project more than three years. Several large media projects help us to test and debug the Editor, to make its core more stable. At the same time we significantly improved the API. Now, it can be used to create any plugin for any task. Hope you enjoy. 😏'
            }
          },
          {
            type: 'image',
            data: {
              url: 'assets/codex2x.png',
              caption: '',
              stretched: false,
              withBorder: true,
              withBackground: false,
            }
          },
        ]
      },
      onReady: function(){
        saveButton.click();
      },
      onChange: function() {
        console.log('something changed');
      }
    });

    /**
     * Saving button
     */
    const saveButton = document.getElementById('saveButton');

    /**
     * Toggle read-only button
     */
    const toggleReadOnlyButton = document.getElementById('toggleReadOnlyButton');
    const readOnlyIndicator = document.getElementById('readonly-state');

    /**
     * Saving example
     */
    saveButton.addEventListener('click', function () {
      editor.save()
        .then((savedData) => {
          cPreview.show(savedData, document.getElementById("output"));
        })
        .catch((error) => {
          console.error('Saving error', error);
        });
    });

    /**
     * Toggle read-only example
     */
    toggleReadOnlyButton.addEventListener('click', async () => {
      const readOnlyState = await editor.readOnly.toggle();

      readOnlyIndicator.textContent = readOnlyState ? 'On' : 'Off';
    });
  </script>

app/views/notes/index.html.erb
<div class="container mt-5 d-flex justify-content-center .flex-column">

  <div class="user-wrapper card-box">
    <img src="https://uploads-ssl.webflow.com/604c98ba045b288eacd85143/604d40ac08cd1b201d16d508_Slice%202.jpg" loading="lazy" alt="" class="profil-pic">
    <h3 class="welcome-name card-title">Welcome back <%=@current_user.first_name%></h3>

    <div class="badge-wrapper"></div>
    <% if policy(Note).create? %>
      <%= form_tag(notes_path, :method => "get",
  class: 'search-form') do %>
        <div class="input-group">
          <%= search_field_tag :search, params[:search], placeholder: "Looking for a keywork in a note...", class: "search-note-input" %>
          <div class="input-group-btn">
            <%= button_tag "Search", :class => 'button create-note-btn color-white w-button pl-4 pr-4 search-btn',:name => nil%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

<!--Search Results-->
    <div class="container">
      <div id="ycourse-list-wrapper-result">
        <% if @search_ycourse
          @search_ycourse.each_with_index do |result,index| %>


            <div class="card-box">
               <% if @search_notes.find(@ycourses[index].id) %>
               <a href="<%= note_path(@search_notes.find(@ycourses[index].id)) %>">
              <img src="https://img.youtube.com/vi/<%= result%>/0.jpg" class="course-thumbnail shadow-lg">
              </a>
              <% end %>
            </div>



          <% end %>
        <% end %>
      </div>


    </div>
<!--Search Results END-->

<!--List Ycourse-->
<div class="container mb-5 pb-5 wrapper">
  <div id="ycourse-list-wrapper">

    <% if @ycourses
      @ycourses_url.each_with_index do |ycourseID, index| %>

        <% if @notes.find(@ycourses[index].id) %>
          <a href="<%= note_path(@notes.find(@ycourses[index].id)) %>">
            <img src="https://img.youtube.com/vi/<%=ycourseID%>/0.jpg" class="course-thumbnail shadow-lg">

          </a>

        <% end %>

      <% end %>
    <% end %>
  </div>
</div>
<!--List Ycourse END-->


<!--JS Code for Search Results-->
<script>
  var result = document.getElementById("ycourse-list-wrapper-result").childElementCount;
  if (result > 0) {
    var ycourse = document.getElementById("ycourse-list-wrapper");
    ycourse.classList.add("d-none");
  }
</script>
<!--JS Code for Search Results END-->

<!--JS Code for Animations-->
<script>
  // ScrollReveal (https://github.com/jlmakes/scrollreveal)

(function scrollReveal() {
  window.sr = ScrollReveal();

  sr.reveal('.card-box', {
    duration   : 600,
    distance   : '20px',
    easing     : 'ease-out',
    origin     : 'bottom',
    reset      : true,
    scale      : 1,
    viewFactor : 0,
    afterReveal  : revealChildren,
  }, 150);

    var revealChildren = sr.reveal('.card-title, .card-text', {
    duration   : 500,
    scale      : 1,
    distance   : '20px',
    origin     : 'bottom',
    reset      : true,
    easing     : 'ease-out',
    viewFactor : 1,
  }, 75);
})();

</script>
<!--JS Code for Animations END-->

app/views/notes/new.html.erb
<%= simple_form_for @note do |f| %>
<% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this Note from being saved:</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title, placeholder: 'My Ruby Rails course'%>
  <%= f.input :visible, inline_label: 'Yes, remember me' %>
  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<div class="y-course-wrapper card-box">
  <!-- Youtube video -->
  <div class="half-screen youtube-video-wrapper">
    <iframe width="100%" height="100%" src="https://www.youtube.com/embed/<%=@ycourseID%>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  <!-- end of video -->

  <!-- the right part of the screen -->
  <div class="half-screen-right card-box">

    <!-- the navigation -->
    <div class="notes-nav">
      <!-- the Back to the notes -->
      <a href="<%= notes_path %>" class="link-block w-inline-block">
        <img src="https://uploads-ssl.webflow.com/604c98ba045b288eacd85143/6053826e1c18ee4b0d70de2b_back-icon.svg" loading="lazy" alt="" class="image-3"><span class="back-to-notes">Back to notes</span>
      </a>

      <!-- The links: Favorite / Delete / Share -->
      <div class="features-wrap">

        <!-- favorite -->

        <% if @current_user.favorited?(@note) %>
          <%= link_to image_tag("https://res.cloudinary.com/dr1gk6cpf/image/upload/v1616576262/Unotes/Heart_Full.svg"), toggle_favorite_path(@note), method: :post, class: 'favorite-false' %>
        <% else %>
          <%= link_to image_tag("https://res.cloudinary.com/dr1gk6cpf/image/upload/v1616576270/Unotes/heart%20_empty.svg"), toggle_favorite_path(@note), method: :post, class: 'favorite-true' %>
        <% end %>


        <!-- share -->
        <a href="#" class="feature-link w-inline-block" id="share-note">
          <img src="https://res.cloudinary.com/the-peacock/image/upload/v1616087286/share_outline_k2ehdj.svg" loading="lazy" alt="">
        </a>

        <!-- delete -->
        <%= link_to image_tag("https://res.cloudinary.com/the-peacock/image/upload/v1616087286/trash_full_solpsf.svg") %>
      </div>
    </div>
    <!-- end of navigation -->

    <!-- The forms fort 1/ the Title & 2/The Visible parameter -->
    <div class="note-title text-right note-forms tag-items">
      <%= simple_form_for(@note) do |f| %>
        <%= f.input :title, input_html: { class: "note-title" }, placeholder: 'My lovely Title' %>
        <!-- Add tags as checkboxes -->
        <%= f.input :tag_list, as: :check_boxes,
          collection: [ "CSS", "HTML", "JavaScript", "Ruby", "SQL", "C++", "Swift", "JAVA" ],
          input_html: { class: "tag-selector" },
          item_wrapper_class: 'tag-item' %>

        <%= f.input :visible, as: :boolean, input_html: { class: "toggle visible" }, value: @note.visible ? false : true %>

        <%= f.button :submit, class: "submit-form", id:"saveButton"%>
      <% end %>
    </div>
    <!-- end of the form -->

    <!-- the editor.js -->
    <div id="editorjs" data-content="<%= @note.json_content %>"></div>

    <!-- the Save Button -->
   <!--  <button id="saveButton">
      Save content
    </button>
 -->
    <!-- Related Notes -->
    <hr>
    <div class="related_notes">
    <p>On the same Thematic</p>
      <ul>
        <% @related_notes.each do |n| %>
          <li class="related_notes_items"> <%= link_to "#{n.title}", note_path(n) %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!--JS Code for Animations-->
<script>
  // ScrollReveal (https://github.com/jlmakes/scrollreveal)


(function scrollReveal() {
  window.sr = ScrollReveal();

  sr.reveal('.card-box', {
    duration   : 600,
    distance   : '20px',
    easing     : 'ease-out',
    origin     : 'bottom',
    reset      : true,
    scale      : 1,
    viewFactor : 0,
    afterReveal  : revealChildren,
  }, 150);

    var revealChildren = sr.reveal('.card-title, .card-text', {
    duration   : 500,
    scale      : 1,
    distance   : '20px',
    origin     : 'bottom',
    reset      : true,
    easing     : 'ease-out',
    viewFactor : 1,
  }, 75);
})();

</script>
<!--JS Code for Animations END-->

app/views/notes/tagged.html.erb
<% @notes.each do |n| %>
  <h2><%= n.title %></h2>
  <p>
    <% n.tag_list.each do |tag| %>
      <%= link_to tag, tagged_path(tag: tag) %>
    <% end %>
  </p>
<% end %>